### ISSUE TITLE
No Longer Able to Cast

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/cordova-plugin-chromecast#42]
For Jellyfin testing, I only have one Android device that I can use. It is currently running 6.0.1, and I cannot update it to anything newer (there are no further updates provided by the manufacturer).

Starting with release 0.9.2, I can no longer cast. When I attempt to bring up the Chromecast dialog, there is this stack trace in the logs:

```09-12 01:06:08.836 24419 24419 D SystemWebChromeClient: file:///android_asset/www/components/chromecast/chromecastplayer.js?v=12: Line 214 : chromecast launching app...
09-12 01:06:08.837 24419 24419 I chromium: [INFO:CONSOLE(214)] "chromecast launching app...", source: file:///android_asset/www/components/chromecast/chromecastplayer.js?v=12 (214)
09-12 01:06:08.847 24419 24474 I art     : Rejecting re-init on previously-failed class java.lang.Class<acidhax.cordova.chromecast.-$$Lambda$r-7qqWexZCMew-ZX5x2dUMjX1R0>
09-12 01:06:08.847 24419 24474 I art     : Rejecting re-init on previously-failed class java.lang.Class<acidhax.cordova.chromecast.-$$Lambda$r-7qqWexZCMew-ZX5x2dUMjX1R0>
09-12 01:06:08.850 24419 24419 I art     : Rejecting re-init on previously-failed class java.lang.Class<acidhax.cordova.chromecast.-$$Lambda$r-7qqWexZCMew-ZX5x2dUMjX1R0>
09-12 01:06:08.850 24419 24419 D AndroidRuntime: Shutting down VM
09-12 01:06:08.852 24419 24419 E AndroidRuntime: FATAL EXCEPTION: main
09-12 01:06:08.852 24419 24419 E AndroidRuntime: Process: org.jellyfin.mobile, PID: 24419
09-12 01:06:08.852 24419 24419 E AndroidRuntime: java.lang.NoClassDefFoundError: acidhax.cordova.chromecast.-$$Lambda$r-7qqWexZCMew-ZX5x2dUMjX1R0
09-12 01:06:08.852 24419 24419 E AndroidRuntime: 	at acidhax.cordova.chromecast.Chromecast$2.run(Chromecast.java:210)
09-12 01:06:08.852 24419 24419 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
09-12 01:06:08.852 24419 24419 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-12 01:06:08.852 24419 24419 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-12 01:06:08.852 24419 24419 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-12 01:06:08.852 24419 24419 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-12 01:06:08.852 24419 24419 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-12 01:06:08.852 24419 24419 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-12 01:06:08.854   832  1420 W ActivityManager:   Force finishing activity org.jellyfin.mobile/.MainActivity
```

The app then closes with a message: "Unfortunately, Jellyfin has stopped working."

If I revert back to our 0.9.1 release, everything is working. This would mean that some commit since July 5th 2019 has changed something that I means I can no longer test this.

**Comment by Lindsay-Needs-Sleep** [comment]
Seems like this might be the same as issue #43?

**Comment by anthonylavado** [comment]
@lindsay-needs-sleep - Yes, seems like it. Looks like they have more info.
