### ISSUE TITLE
(1.0.0) (Android) selectRoute - Crash on select group route

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [jellyfin/cordova-plugin-chromecast#48]
This occurs intermittently when trying to join a group route on 1.0.0.  Possibly occurs in 0.x as well.

```
09-26 12:45:47.560 11533-11533/com.testy_pants.plugin_tests E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.miloproductionsinc.plugin_tests, PID: 11533
    java.lang.NullPointerException
        at androidx.mediarouter.media.MediaRouter$GlobalMediaRouter.setSelectedRouteInternal(MediaRouter.java:2633)
        at androidx.mediarouter.media.MediaRouter$GlobalMediaRouter.selectRoute(MediaRouter.java:2120)
        at androidx.mediarouter.media.MediaRouter$GlobalMediaRouter.selectRoute(MediaRouter.java:2108)
        at androidx.mediarouter.media.MediaRouter.selectRoute(MediaRouter.java:406)
        at acidhax.cordova.chromecast.ChromecastConnection$2$1.onRouteUpdate(ChromecastConnection.java:183)
        at acidhax.cordova.chromecast.ChromecastConnection$ScanCallback.onFilteredRouteUpdate(ChromecastConnection.java:590)
        at acidhax.cordova.chromecast.ChromecastConnection$ScanCallback.access$1200(ChromecastConnection.java:539)
        at acidhax.cordova.chromecast.ChromecastConnection$5.run(ChromecastConnection.java:410)
        at android.app.Activity.runOnUiThread(Activity.java:4713)
        at acidhax.cordova.chromecast.ChromecastConnection.startRouteScan(ChromecastConnection.java:389)
        at acidhax.cordova.chromecast.ChromecastConnection$2.run(ChromecastConnection.java:245)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
```

Possibly slightly related to #49
Both problems *seem* to be caused by routes temporarily and quickly becoming unavailable before we are actually able to join.

### Observations
* I have observed it on my Android 4.4 device but not on my 7.0 device.  
* I believe this issue is timing issue (see above)
* I believe the main reason it is only happening on my 4.4 is because it is so much slower.  (eg. can take 8s to join a route.)
* The problem is much worse when debugging.  
  * When I have it hooked up the to the Android Studio debugger it will crash on the 2nd call to selectRoute on average.  I don't think I have ever gotten past 4 runs.
  * With no debugging, it is at least 20+ average, sometimes I spam select route 50 times and no crash.
* Edit: Interestingly, if we catch the exception, and just let it continue scanning for the route (aka. basically letting it retry), it will hit: 
  * SessionManagerListener.onSessionEnded (errCode == 0 (success))
  * It hits this before a valid route is found again
  * It then succeeds in joining the re-found route
  * It appears that it likely goes through the same event pattern as #49

**Comment by Lindsay-Needs-Sleep** [comment]
Added the retry mechanism as described in the issue.  From the client-side everything appears to work.  Just takes slightly longer to a join a route sometimes.
