### ISSUE TITLE
App crashes after a while of casting

### ISSUE THREAD

**Issue by rongchaua** [jellyfin/cordova-plugin-chromecast#52]
I've successfully cast the audio to cast device. Then I just let the app open for some minutes then the app has been crashed.

Logcat shows me this error.

> 2019-10-05 15:02:32.807 1022-1022/com.hintdesk.sachxua D/AndroidRuntime: Shutting down VM
2019-10-05 15:02:32.814 1022-1022/com.hintdesk.sachxua E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hintdesk.sachxua, PID: 1022
    java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
        at com.google.android.gms.common.internal.BaseGmsClient.checkConnected(Unknown Source:198)
        at com.google.android.gms.internal.cast.zzdd.getVolume(Unknown Source:136)
        at com.google.android.gms.cast.Cast$CastApi$zza.getVolume(Unknown Source:23)
        at acidhax.cordova.chromecast.ChromecastSession.createSessionObject(ChromecastSession.java:471)
        at acidhax.cordova.chromecast.ChromecastSession.onConnectionSuspended(ChromecastSession.java:624)
        at com.google.android.gms.common.internal.GmsClientEventManager.onUnintentionalDisconnection(Unknown Source:49)
        at com.google.android.gms.common.api.internal.zaaw.zab(Unknown Source:319)
        at com.google.android.gms.common.api.internal.zaah.onConnectionSuspended(Unknown Source:42)
        at com.google.android.gms.common.api.internal.zabe.onConnectionSuspended(Unknown Source:106)
        at com.google.android.gms.common.api.internal.zaq.onConnectionSuspended(Unknown Source:9)
        at com.google.android.gms.common.internal.zaf.onConnectionSuspended(Unknown Source:4)
        at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source:39)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-10-05 15:02:32.823 1193-1204/? W/ActivityManager:   Force finishing activity com.hintdesk.sachxua/.MainActivity

**Comment by Lindsay-Needs-Sleep** [comment]
@rongchaua 
If you are still using the chromecast plugin, have you had a chance to try the newest version?

I am wondering if the newest version has fixed this issue.  

If the problem is still there, can you post a new stack trace?

Thanks! :D

**Comment by Lindsay-Needs-Sleep** [comment]
Closing due to inactivity.  Feel free to re-open if this is still an issue with the 1.x+ versions of the plugin.
