### ISSUE TITLE
App Get CRASHED on Android 12V. (Ionic 5)

### ISSUE THREAD

**Issue by DevGupta004** [jellyfin/cordova-plugin-chromecast#82]
--------- beginning of crash
2022-09-06 10:51:50.814 29922-29922/com.d.devott E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.d.devott, PID: 29922
    java.lang.IllegalArgumentException: com.d.devott: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
        at com.google.android.gms.internal.cast.zzah.zza(Unknown Source:32)
        at com.google.android.gms.cast.framework.CastSession$zzb.onResult(Unknown Source:12)
        at com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler.handleMessage(com.google.android.gms:play-services-base@@18.0.0:6)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by cvium** [comment]
This is an archived repository. We do not provide any support for this plugin.
